/** Human names for audited actions, shown on the Activity page. */
export const ACTION_LABELS: Record<string, string> = {
  fulfilOrder: "Fulfilled an egg order",
  declineOrder: "Declined an egg order",
  markPaid: "Marked an invoice paid",
  markUnpaid: "Marked an invoice unpaid",
  recordPayment: "Recorded a payment",
  deletePayment: "Deleted a payment",
  fulfilRequest: "Fulfilled a feed request",
  declineRequest: "Declined a feed request",
  setCratePrice: "Changed the crate price",
  inviteStaff: "Invited a team member",
  inviteBuyer: "Invited a buyer",
  revokeInvite: "Revoked an invite",
  setStaffRole: "Changed a role",
  setUserDisabled: "Changed someone's access",
  addCustomer: "Added a buyer",
  addOrder: "Ordered for a buyer",
  addInvoice: "Recorded a sale",
  addProduction: "Recorded egg collection",
  addEggMove: "Recorded an egg movement",
  logFeedUse: "Logged feed use",
  addBatch: "Placed a batch",
  recordMortality: "Recorded deaths",
  closeBatch: "Closed a batch",
  addHouse: "Added a house",
  addLayersFeedDelivery: "Recorded a layers feed delivery",
  addWaterLog: "Logged water",
  addVaccination: "Recorded a vaccination",
  addMedication: "Recorded a medication",
  addIngredient: "Added an ingredient",
  addDelivery: "Recorded an ingredient delivery",
  addProduct: "Added a feed product",
  addRun: "Recorded a production run",
  addFeedSale: "Recorded a feed sale",
  addFeedRequest: "Raised a feed request",
  addInvItem: "Added a store item",
  addInvMove: "Recorded a store movement",
  updateCustomer: "Edited a buyer",
  updateIngredient: "Edited an ingredient",
  updateProduct: "Edited a product",
  updateHouse: "Edited a house",
  updateInvItem: "Edited a store item",
  deleteEntry: "Deleted an entry",
  emailInvoice: "Emailed an invoice",
  emailInvite: "Emailed an invite link",
  placeOrder: "Placed an order (portal)",
  acceptInvite: "Accepted an invite",
};

export const actionLabel = (action: string) => ACTION_LABELS[action] ?? action;
