-- AlterTable
ALTER TABLE "feed_products" ALTER COLUMN "bagKg" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "feed_use" ALTER COLUMN "kg" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "ingredient_deliveries" ALTER COLUMN "kg" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "pricePerKg" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "ingredients" ALTER COLUMN "reorderKg" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "inv_items" ALTER COLUMN "reorder" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "inv_moves" ALTER COLUMN "qty" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "layers_feed_deliveries" ALTER COLUMN "kg" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "medications" ALTER COLUMN "qtyUsed" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "production_runs" ALTER COLUMN "outputKg" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "run_lines" ALTER COLUMN "kg" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "pricePerKg" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "vaccinations" ALTER COLUMN "qtyUsed" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "water_logs" ALTER COLUMN "litres" SET DATA TYPE DOUBLE PRECISION;
